name: Clojure CI - Build Blog

on:
  push:
    branches: [ main ]

jobs:

  build-blog:
    name: Build Blog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Blog Files
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          apt-get install build-essential
          brew install gcc
          brew install borkdude/brew/babashka
          bb quickblog render

      - name: Commit Rendered Blog Files
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Render blog files'
          author_name: GitHub Actions
          author_email: actions@github.com
